# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko --version 2.3.0 -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 4.1.5 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib install linc_luajit
  - haxelib list

# No tests idk lol
build_script:
  - haxelib run lime build windows
  # haxelib run lime build linux

artifacts:
  - path: export/release/windows/bin
    name: KadeEngine-Windows
    type: zip
