# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
        
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c

      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK %ANDROID_SDK_ROOT%
          haxelib run lime config ANDROID_NDK_ROOT %ANDROID_NDK_ROOT%
          haxelib run lime config JAVA_HOME %JAVA_HOME%
          haxelib run lime config ANDROID_SETUP true
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm android
          haxelib git linc_luajit https://github.com/MasterEric/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit.git
          haxelib install actuate 
          haxelib list
          haxelib run lime build android
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug
